//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceRecognition.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FaceRecognition.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Test Face Recognition.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Features Block.
        /// </summary>
        public static string ExtractFeaturesWindow_Title {
            get {
                return ResourceManager.GetString("ExtractFeaturesWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection Face.
        /// </summary>
        public static string FaceDetectionWindow_Title {
            get {
                return ResourceManager.GetString("FaceDetectionWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemporaryData\RecognitionMehodsResults.xls.
        /// </summary>
        public static string FileName_ExcelResults {
            get {
                return ResourceManager.GetString("FileName_ExcelResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemporaryData\OneLayer_NeuronNet.xml.
        /// </summary>
        public static string FileName_OneLayer_NeuronNet {
            get {
                return ResourceManager.GetString("FileName_OneLayer_NeuronNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemporaryData\RecognizedFaces.xml.
        /// </summary>
        public static string FileName_RecognizedFaces {
            get {
                return ResourceManager.GetString("FileName_RecognizedFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemporaryData\SelectedRecognitionMethods.xml.
        /// </summary>
        public static string FileName_SelectedRecognitionMethods {
            get {
                return ResourceManager.GetString("FileName_SelectedRecognitionMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemporaryData\TestFaces.xml.
        /// </summary>
        public static string FileName_TestFaces {
            get {
                return ResourceManager.GetString("FileName_TestFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemporaryData\TestImages.xml.
        /// </summary>
        public static string FileName_TestImages {
            get {
                return ResourceManager.GetString("FileName_TestImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemporaryData\ThreeLayer_NeuronNet.xml.
        /// </summary>
        public static string FileName_ThreeLayer_NeuronNet {
            get {
                return ResourceManager.GetString("FileName_ThreeLayer_NeuronNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemporaryData\TrainFaces.xml.
        /// </summary>
        public static string FileName_TrainFaces {
            get {
                return ResourceManager.GetString("FileName_TrainFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemporaryData\TrainImages.xml.
        /// </summary>
        public static string FileName_TrainImages {
            get {
                return ResourceManager.GetString("FileName_TrainImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemporaryData\TwoLayer_NeuronNet.xml.
        /// </summary>
        public static string FileName_TwoLayer_NeuronNet {
            get {
                return ResourceManager.GetString("FileName_TwoLayer_NeuronNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Face Recognition Algorithms.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &apos;Selection Train And Test Images&apos; Window.
        /// </summary>
        public static string MainWindow_Toolbar_ImagesDbButon_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_Toolbar_ImagesDbButon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string PreprocessingWaitWindow_ProgressBar_Title {
            get {
                return ResourceManager.GetString("PreprocessingWaitWindow_ProgressBar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessing Wait Window.
        /// </summary>
        public static string PreprocessingWaitWindow_Title {
            get {
                return ResourceManager.GetString("PreprocessingWaitWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Face Recognition Methods.
        /// </summary>
        public static string RecognitionMethodsWindow_Title {
            get {
                return ResourceManager.GetString("RecognitionMethodsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select faces for train face recognition algorithms and test face recognition algorithms.
        /// </summary>
        public static string TrainAndTestImagesWindow_Title {
            get {
                return ResourceManager.GetString("TrainAndTestImagesWindow_Title", resourceCulture);
            }
        }
    }
}
